# Generated by Django 3.1.5 on 2021-02-28 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_category_story'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notes.category'),
        ),
        migrations.DeleteModel(
            name='Story',
        ),
    ]
