# Generated by Django 3.1.5 on 2021-02-28 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_remove_signup_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='branch',
        ),
        migrations.DeleteModel(
            name='Signup',
        ),
    ]
