# Generated by Django 3.1.5 on 2021-02-28 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_auto_20210301_0155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='subject',
            field=models.CharField(max_length=22),
        ),
    ]
