# Generated by Django 3.1.5 on 2021-03-01 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0007_auto_20210301_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_index=True, max_length=150, unique=True),
        ),
    ]
